---
- name: Hue motion → Job (final)
  hosts: all

  sources:
    - ipvsean.hue_booth_demo.mqtt_simple:
        host: mqtt-broker
        port: 1883
        topics:
          - "hue/motion/#"
        tls: false

  rules:
    # Fire ONLY when the motion flag is true.
    # Put this FIRST so no broader rule eats the event.
    - name: Motion detected -> launch JT
      condition:
        all:
          - event.payload is defined
          - event.payload.motion is defined
          - event.payload.motion.motion        # truthy check
      throttle:
        once_within: 5    # avoid rapid re-triggers; tweak as you like
      actions:
        - debug:
            msg: >-
              LAUNCHING JT: sensor={{ event.payload.id }}
              at={{ event.payload.motion.motion_report.changed | default('') }}
        - run_job_template:
            name: Demo Job Template
            organization: Default
            job_args:
              extra_vars:
                sensor_id: "{{ event.payload.id }}"
                id_v1: "{{ event.payload.id_v1 | default('') }}"
                changed_at: "{{ event.payload.motion.motion_report.changed | default('') }}"

    # Optional: log every motion event (true/false) for visibility.
    # Keep this AFTER the job rule.
    - name: Motion event observed (log)
      condition:
        all:
          - event.payload is defined
          - event.payload.motion is defined
      action:
        print_event: {}
