---
- name: Hue motion → AAP Demo Job
  hosts: all

  sources:
    - ipvsean.hue_booth_demo.mqtt_simple:
        host: mqtt-broker
        port: 1883
        topics:
          - hue/motion/#
        tls: false

  rules:
    # Sanity rule: prove we match every "motion" event
    - name: Sanity: saw a motion-type event
      condition:
        all:
          - event.payload is defined
          - event.payload.type == "motion"
      action:
        debug:
          msg: >-
            MOTION EVENT: id={{ event.payload.id }}
            active={{ event.payload.motion.motion | default('n/a') }}
            at={{ event.payload.motion.motion_report.changed | default('') }}

    # Fire only when motion is true
    - name: Motion detected (fire job)
      condition:
        all:
          - event.payload is defined
          - event.payload.type == "motion"
          - event.payload.motion is defined
          - event.payload.motion.motion == true
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
          job_args:
            extra_vars:
              sensor_id: "{{ event.payload.id }}"
              id_v1: "{{ event.payload.id_v1 | default('') }}"
              changed_at: "{{ event.payload.motion.motion_report.changed | default('') }}"
