---
- name: Hue motion → AAP Demo Job
  hosts: all

  sources:
    - ipvsean.hue_booth_demo.mqtt_simple:
        host: mqtt-broker
        port: 1883
        topics:
          - hue/motion/#
        tls: false

  rules:
    - name: Motion detected
      condition: >-
        event.payload and
        event.payload.type == "motion" and
        event.payload.motion and
        event.payload.motion.motion
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
          job_args:
            extra_vars:
              sensor_id: "{{ event.payload.id }}"
              id_v1: "{{ event.payload.id_v1 | default('') }}"
              changed_at: "{{ event.payload.motion.motion_report.changed | default('') }}"
