---
- name: Hue motion → Sanity checks (v2)
  hosts: all

  sources:
    - ipvsean.hue_booth_demo.mqtt_simple:
        host: mqtt-broker
        port: 1883
        topics: [ "hue/motion/#" ]
        tls: false

  rules:
    - name: R1 print_event (all) (v2)
      condition: true
      action:
        print_event: {}

    - name: R2 print_event (type==motion) (v2)
      condition:
        all:
          - event.payload is defined
          - event.payload["type"] == "motion"
      action:
        print_event: {}

    - name: R3 print_event (motion==true) (v2)
      condition:
        all:
          - event.payload is defined
          - event.payload["type"] == "motion"
          - event.payload.motion is defined
          - event.payload.motion.motion
      action:
        print_event: {}
