---
- name: Hue motion → Job (final)
  hosts: all

  sources:
    - ipvsean.hue_booth_demo.mqtt_simple:
        host: mqtt-broker
        port: 1883
        topics: [ "hue/motion/#" ]
        tls: false

  rules:
    # Fire ONLY when motion is true
    - name: Motion detected -> Job
      condition:
        all:
          - event.payload.motion is defined
          - event.payload.motion.motion == true
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
          job_args:
            extra_vars:
              sensor_id: "{{ event.payload.id }}"
              id_v1: "{{ event.payload.id_v1 | default('') }}"
              changed_at: "{{ event.payload.motion.motion_report.changed | default('') }}"

    # Optional: log any motion events (true *or* false) for visibility
    - name: Motion event observed
      condition:
        all:
          - event.payload.motion is defined
      action:
        print_event: {}

    # Optional: last resort catch-all (put LAST!)
    - name: Catch-all (debug)
      condition: true
      action:
        print_event: {}
