---
- name: Hue motion → Sanity checks (v3)
  hosts: all

  sources:
    - ipvsean.hue_booth_demo.mqtt_simple:
        host: mqtt-broker
        port: 1883
        topics: [ "hue/motion/#" ]
        tls: false

  rules:
    # R1: baseline — prove rules run at all (prints EVERY event)
    - name: R1 print_event (all) (v3)
      condition: true
      action:
        print_event: {}

    # R1.5: echo what the engine/Jinja sees for the fields we use in conditions
    - name: R1.5 echo fields (v3)
      condition: true
      action:
        debug:
          msg: >-
            TYPE_DOT={{ event.payload.type | default('~UNDEF~') }}
            TYPE_BRACKET={{ event.payload["type"] | default('~UNDEF~') }}
            MOTION_FLAG={{ event.payload.motion.motion | default('~UNDEF~') }}

    # R2: match when payload["type"] == "motion"
    - name: R2 print_event (type==motion) (v3)
      condition:
        all:
          - event.payload is defined
          - event.payload["type"] == "motion"
      action:
        print_event: {}

    # R3: match when motion flag is truthy
    - name: R3 print_event (motion==true) (v3)
      condition:
        all:
          - event.payload is defined
          - event.payload["type"] == "motion"
          - event.payload.motion is defined
          - event.payload.motion.motion
      action:
        print_event: {}
