---
- name: Hue motion → Job (final v4)
  hosts: all

  sources:
    - ipvsean.hue_booth_demo.mqtt_simple:
        host: mqtt-broker
        port: 1883
        topics:
          - "hue/motion/#"
        tls: false

  rules:
    # Fire ONLY when motion goes true (put this FIRST)
    - name: Motion detected -> print + launch JT
      condition:
        any:
          - event.payload.motion.motion            # truthy
          - event.payload.motion.motion == true    # explicit boolean
      actions:
        - print_event: {}   # proves the rule matched
        - debug:
            msg: >-
              LAUNCHING JT: sensor={{ event.payload.id }}
              at={{ event.payload.motion.motion_report.changed | default('') }}
        - run_job_template:
            name: Demo Job Template
            organization: Default
            job_args:
              extra_vars:
                sensor_id: "{{ event.payload.id }}"
                id_v1: "{{ event.payload.id_v1 | default('') }}"
                changed_at: "{{ event.payload.motion.motion_report.changed | default('') }}"

    # Visibility for ALL motion events (true and false)
    - name: Motion event observed
      condition:
        all:
          - event.payload.motion is defined
      action:
        print_event: {}
