version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/de-supported-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system:
    - gcc
    - make
    - redhat-rpm-config
    - python3.11-devel
    - systemd-devel
    - pkgconf-pkg-config

options:
  package_manager_path: /usr/bin/microdnf
